/**
 * Differential CSV reconciliation against the Python reference golden
 * corpus (tests/golden/csv-corpus.json, generated by scripts/golden_csv.py
 * at development time). Compares actual report OBJECTS, report BYTES
 * (hex), digests, error codes and error MESSAGES — including Python list
 * reprs embedded in messages.
 */

import { assertEquals, assertThrows } from "./helpers.ts";
import {
  parseCsv,
  reconcileCsvs,
  reportBytes,
  reportDigest,
} from "../src/appservices/csv_reconcile.ts";
import { ContractError } from "../src/contracts/common.ts";

interface GoldenCase {
  name: string;
  ok: boolean;
  report?: Record<string, unknown>;
  reportBytesHex?: string;
  reportSha256?: string;
  errorCode?: string;
  error?: string;
}

interface GoldenCorpus {
  schemaVersion: number;
  cases: GoldenCase[];
  rawProbes: Array<
    { name: string; text: string; records: string[][]; endLines: number[]; lineNum: number }
  >;
}

const corpus = JSON.parse(
  new TextDecoder().decode(Deno.readFileSync(new URL("./golden/csv-corpus.json", import.meta.url))),
) as GoldenCorpus;

const CASE_INPUTS: Record<
  string,
  { left: string; right: string; joinKey: string; delimiter?: string; ignoreColumns?: string[] }
> = {
  "sample-journey": {
    left:
      "sku,name,price_usd,stock\nAUR-001,Aurora Gooseneck Kettle,95.00,12\nAUR-002,Aurora Travel Kettle,59.00,30\nBRW-010,Oakline Pour-Over Brewer,42.00,8\nMSC-100,Morning Scale,25.00,0\nSLM-007,Summer Linen Set,120.00,4\n",
    right:
      "sku,name,price_usd,stock,lead_days\nAUR-001,Aurora Gooseneck Kettle,95.00,12,3\nAUR-002,Aurora Travel Kettle,54.00,30,5\nBRW-010,Oakline Pour-Over Brewer,42.00,8,4\nMSC-100,Morning Scale,25.00,0,21\nDNR-030,Dawn Mug Set,18.00,60,2\nDNR-030,Dawn Mug Set,18.00,55,2\n",
    joinKey: "sku",
  },
  "chinese-fields-and-keys": {
    left: "型号,名称,价格\nK-01,电热水壶,159.00\nK-02,旅行壶,89.50\n",
    right: "型号,名称,价格,备注\nK-01,电热水壶,159.00,安静\nK-03,保温杯,59.00,\n",
    joinKey: "型号",
  },
  "multiline-quoted-physical-lines": {
    left: 'id,desc\nA,"line1\nline2"\nB,single\nC,"has ""quotes"", and , commas"\n',
    right: 'id,desc\nA,"line1\nline2"\nC,different\n',
    joinKey: "id",
  },
  "empty-join-keys-and-blank-lines": {
    left: "k,v\n\nX,1\n,2\n,3\n\nY,4\n",
    right: "k,v\nX,1\n,9\nZ,5\n",
    joinKey: "k",
  },
  "ambiguous-duplicates-both-sides": {
    left: "k,v\nA,1\nA,2\nB,3\nC,4\nC,5\nC,6\nD,7\n",
    right: "k,v\nA,9\nB,3\nB,8\nC,4\nE,1\nE,1\nE,2\n",
    joinKey: "k",
  },
  "schema-divergence-insufficient": {
    left: "k,left_only\nA,1\n",
    right: "k,right_col\nA,2\n",
    joinKey: "k",
  },
  "all-shared-ignored": {
    left: "k,shared\nA,1\n",
    right: "k,shared\nA,2\n",
    joinKey: "k",
    ignoreColumns: ["shared"],
  },
  "duplicate-header-rejected": {
    left: "sku,price,price\nA,1,2\n",
    right: "sku,price\nA,1\n",
    joinKey: "sku",
  },
  "empty-header-name-rejected": {
    left: "sku, ,price\nA,1,2\n",
    right: "sku,price\nA,1\n",
    joinKey: "sku",
  },
  "ragged-row-rejected": {
    left: "sku,price\nA,1,EXTRA\n",
    right: "sku,price\nA,1\n",
    joinKey: "sku",
  },
  "join-key-missing": { left: "sku,price\nA,1\n", right: "code,price\nA,1\n", joinKey: "sku" },
  "unsupported-delimiter": {
    left: "sku|price\nA|1\n",
    right: "sku|price\nA|1\n",
    joinKey: "sku",
    delimiter: "|",
  },
  "semicolon-delimiter": {
    left: "k;v\nA;1\nB;2\n",
    right: "k;v\nA;1\nC;3\n",
    joinKey: "k",
    delimiter: ";",
  },
  "crlf-and-cr-line-endings": {
    left: "k,v\r\nA,1\r\nB,2\r",
    right: "k,v\r\nA,9\r\nC,3\r\n",
    joinKey: "k",
  },
  "lenient-quotes-and-unterminated": {
    left: 'k,v\nA,"quoted"\nB,q"uote\nC,"unterminated\nD,"a""b"x\nE,""\n',
    right: 'k,v\nA,quoted\nB,q"uote\nC,unterminated\nD,a"bx\nE,\n',
    joinKey: "k",
  },
  "utf8-bom-stripped": { left: "﻿k,v\nA,1\n", right: "k,v\nA,2\n", joinKey: "k" },
  "empty-right-file": { left: "k,v\nA,1\n", right: "", joinKey: "k" },
  "header-only-sides": { left: "k,v\n", right: "k,v\n", joinKey: "k" },
  "trailing-delimiter-and-blank-at-eof": {
    left: "k,v\nA,1,\nA,1,\n\n",
    right: "k,v\nA,1,\n",
    joinKey: "k",
  },
  "changed-values-in-context": {
    left: "k,price,stock,note\nA,1.00,1,first\nB,2.00,2,second\n",
    right: "k,price,stock\nA,1.50,1\nB,2.00,9\n",
    joinKey: "k",
    ignoreColumns: ["note"],
  },
};

function hex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

Deno.test({
  name: "differential: every golden case matches the Python reference exactly",
  fn() {
    assertEquals(corpus.cases.length, Object.keys(CASE_INPUTS).length, "case table drift");
    for (const golden of corpus.cases) {
      const input = CASE_INPUTS[golden.name];
      if (input === undefined) throw new Error(`no TS input for ${golden.name}`);
      if (golden.ok) {
        const report = reconcileCsvs(
          new TextEncoder().encode(input.left),
          new TextEncoder().encode(input.right),
          {
            joinKey: input.joinKey,
            delimiter: input.delimiter,
            ignoreColumns: input.ignoreColumns,
          },
        );
        assertEquals(
          JSON.parse(JSON.stringify(report)),
          JSON.parse(JSON.stringify(golden.report)),
          `${golden.name}: report object`,
        );
        const bytes = reportBytes(report);
        assertEquals(hex(bytes), golden.reportBytesHex, `${golden.name}: report BYTES`);
        assertEquals(reportDigest(report), golden.reportSha256, `${golden.name}: report digest`);
      } else {
        const exc = assertThrows(
          () =>
            reconcileCsvs(
              new TextEncoder().encode(input.left),
              new TextEncoder().encode(input.right),
              {
                joinKey: input.joinKey,
                delimiter: input.delimiter,
                ignoreColumns: input.ignoreColumns,
              },
            ),
          ContractError,
          undefined,
          golden.name,
        ) as ContractError;
        assertEquals(exc.code, golden.errorCode, `${golden.name}: error code`);
        assertEquals(exc.message, golden.error, `${golden.name}: error message`);
      }
    }
  },
});

Deno.test({
  name: "differential: raw csv.reader probe parity (records + final line_num)",
  fn() {
    for (const probe of corpus.rawProbes) {
      let parsed;
      try {
        parsed = parseCsv(new TextEncoder().encode(probe.text), "probe.csv", ",");
      } catch (exc) {
        // probes that fail header validation still parse record-wise; only
        // compare when parsing succeeded (probe inputs are header-valid)
        throw new Error(`${probe.name}: unexpected parse failure: ${exc}`);
      }
      assertEquals(parsed.allRecords, probe.records, `${probe.name}: records`);
      assertEquals(parsed.allEndLines, probe.endLines, `${probe.name}: per-record end lines`);
    }
  },
});

Deno.test({
  name: "physical start-line tracking for multiline records (vs corpus refs)",
  fn() {
    const input = new TextEncoder().encode('id,desc\nA,"line1\nline2"\nB,single\n');
    const parsed = parseCsv(input, "probe.csv", ",");
    assertEquals(parsed.rows[0].line, 2, "A starts at line 2");
    assertEquals(parsed.rows[1].line, 4, "B starts after the 2-line quoted record");
  },
});
